var StarterSword = [{
		html: '<div id="0" class="tag">Starter Sword</div>',
		top: 300,
		left: 1,		
		id : 0,
		sub: 0,
	},{
		html: '<div id="1" class="tag">Single Sided</div>',
		top: 200,
		left: 200,
		id : 1,
		sub: 0,
	},{
		html: '<div id="2" class="tag">Double Sided</div>',
		top: 400,
		left: 200,
		id : 2,
		sub: 0,
	},{
		html: '<div id="3" class="tag">Knock out</div>',
		top: 150,
		left: 400,
		id : 3,
		sub: 1,
	},{
		html: '<div id="4" class="tag">Dual Weild</div>',
		top: 250,
		left: 400,
		id : 4,
		sub: 1,
	},{
		html: '<div id="5" class="tag">Weight Cap = 2.5 lb</div>',
		top: 450,
		left: 400,
		id : 5,
		sub: 2,
	},{
		html: '<div id="6" class="tag">Material Cap = Copper</div>',
		top: 350,
		left: 600,
		id : 6,
		sub: 5,
		sub2: 4,
	},{
		html: '<div id="7" class="tag">Slicing Wirlwind</div>',
		top: 250,
		left: 600,
		id : 7,
		sub: 4,
	},{
		html: '<div id="8" class="tag">Blade Of Time Lost Memories</div>',
		top: 100,
		left: 800,
		id : 8,
		sub: 7,
	},{
		html: '<div id="9" class="tag">Sharpness Cap = 10° cutting angle</div>',
		top: 250,
		left: 800,
		id : 9,
		sub: 7,
	},{
		html: '<div id="10" class="tag">Material Cap = Bronze</div>',
		top: 350,
		left: 850,
		id : 10,
		sub: 6,
	},{
		html: '<div id="11" class="tag">Reaper Of Lost Hope</div>',
		top: 400,
		left: 1200,
		id : 11,
		sub: 10,
		sub2: 12,
	},{
		html: '<div id="12" class="tag">Infernal Bane Star</div>',
		top: 500,
		left: 1000,
		id : 12,
	},{
		html: '<div id="13" class="tag">Length Cap = 5 ft</div>',
		top: 550,
		left: 600,
		id : 13,
		sub: 5,
	},{
		html: '<div id="14" class="tag">Weight Cap = 3 lb</div>',
		top: 450,
		left: 800,
		id : 14,
		sub: 13,
	},{
		html: '<div id="15" class="tag">Sharpness Cap = 11° cutting angle</div>',
		top: 575,
		left: 850,
		id : 15,
		sub: 13,
	},{
		html: '<div id="16" class="tag">Quake</div>',
		top: 650,
		left: 770,
		id : 16,
		sub: 13,
}];